### ISSUE TITLE
В продолжение моего сообщения на addons.mozilla.org

### ISSUE THREAD

**Issue by greyrat116** [NC22/KellyC-Show-YouTube-Dislikes#10]
Баг в старой мобильной версии ютуба вылечился с версией 1.1.5.3. В разных браузерах разные версии (новая и старая) мобильного ютуба показываются. Но на том же Firefox 52 хотел переключить на новый мобильный вид с помощью замены юзерагента, но почему-то не вышло.
Да, можно версию минимальную поднять до 52 (последняя для XP и виста). Firefox 48 был  последний для процессоров без SSE2 и первой версией где заработали расширения в новом формате.

**Comment by NC22** [comment]
принято. Если есть какие-то замечания можно выделить в отдельные тикеты, мб со временем проверю.
