### ISSUE TITLE
Совместимость со стилями возвращающими старый дизайн ютуба

### ISSUE THREAD

**Issue by IvanRussian15** [NC22/KellyC-Show-YouTube-Dislikes#11]
У меня обновился интерфейс ютуба. теперь он чмошно скруглённый.
Я сразу полез искать стили чтоб вернуть старый интерфейс. Он оказывается из ютуба не удалён, а всего лишь скрыт. Но из-за этого твоё расширение работает не очень правильно, в старом интерфейсе показывает только дизлайки, в новом всё остальное причём не очень ровно *(особенно если ещё и savefrom включить)*. Есть возможность сделать как-то совместимость?

[Стиль этот на Firefox ставил](https://userstyles.world/style/6944/youtube-old-layout)

Полностью сохранённый файл в качестве тушки для биться могу скинуть, но только по закрытому каналу (почта, например)

**Comment by NC22** [comment]
@IvanRussian15 Привет. Думаю с дополнительными надстройками слишком много коллизий будет. Только если кто то протестит сам все возможные комбинации, но думаю будет сложно учитывая что нет возможности нормально тестить переключаясь между всеми возможными стилями ( там по меньшей мере уже 4 сейчас и так из коробки - условно "старый", пере трансформированный новый без скруглений, со скруглениями, с разделением скругленных кнопок - у каждого есть свои особенности по структуре нарушающие уже реализованые селекторы - каждый из стилей все еще может показыватся определенным регионам \ пользователям исходя из А\Б тестирования)

пока ориентируюсь на тот который отображается у меня https://catface.ru/userfiles/media/udata_1667409888_iwbhrkow.png

старый стиль тоже должен поддерживаться без проблем если он у тебя отображается нативно непосредственно самим ютубом

**Comment by IvanRussian15** [comment]
> пока ориентируюсь на тот который отображается у меня

![2022-11-02_20-31-12](https://user-images.githubusercontent.com/48278585/199560554-3b49f77b-b09a-4b05-ba09-70c06aafb87e.png)

Примерно он же. Только белый и чуть поменьше при большем размере кнопок из-за русского языка.

**Comment by IvanRussian15** [comment]
Там в древе под ним лежит старый но с display:none

![2022-11-02_20-33-55](https://user-images.githubusercontent.com/48278585/199561067-8caedaf8-ae42-42ca-ad3d-c4816a22a321.png)

С указанным выше стилем (который по сути просто скрывает новый интерфейс и включает отображение нового) вот так выглядит.

**Comment by NC22** [comment]
@IvanRussian15 

> Примерно он же. Только белый и чуть поменьше при большем размере кнопок из-за русского языка

Ага, в масштабе по умолчанию этот дизайн и в Full hd не всегда все блоки выводит, масштабирование до 70-80% обычно помогает.

> Ну у тебя расширение не взаимодействует с этим вот старым. Находит новый и работает с ним. Возможно потому что он раньше лежит. Не то чтобы это не правильно...

Там привязано к логике ютуба - новые блоки содержатся в контейнере ytd-watch-metadata - если новый дизайн отключен, блок ytd-watch-metadata имеет аттрибут disable-upgrade + hidden и в таком случае расширение использует старый контейнер для привязки своих блоков. Можно добавить режим для совместимости и проверять через текущее состояние стилей по display none, но это будет уже косвенный фактор не дающий однозначности - блоки при рендере могут и скрываться на время, надо проверять что все будет ок. Пока наверное подожду чего еще ютуб выкинет, а то у них семь пятниц на неделе, мб устаканится какой-то конкретный диз \ окончательно удалят ошметки старого чтобы те кто хочет вернуть старый вид это не абузили, а сделали полноценное переоформление уже новых блоков под "старый" стиль.

**Comment by IvanRussian15** [comment]
> блоки при рендере могут и скрываться на время, надо проверять что все будет ок
Или сделать флажок в настройках для продвинутых пользователей. Т.с. Можно и вот так, но без гарантий.

**Comment by TheNonSmoker** [comment]
I think Dislike API has been dissolved! YouTube's dislikes are hidden for permanent now!

**Comment by theAkito** [comment]
The extension still works for me, at least with its own API.

**Comment by IvanRussian15** [comment]
Стиль эволюционировал, и теперь позволяет этому расширению отображать рейтинг и дизлайки.
