### ISSUE TITLE
It keeps saying "Data service not respond" and I keep clicking Try Again and refreshing the page, but it still says it

### ISSUE THREAD

**Issue by WyattLife** [NC22/KellyC-Show-YouTube-Dislikes#12]
![glitch](https://user-images.githubusercontent.com/98365341/200160978-36cb6354-7c97-4e5d-9f9f-ebf21ea9c9f1.png)

**Comment by NC22** [comment]
@WyattLife Hi. This just means that data server is not responding, its not related to extension itself. According to feedback from https://discord.gg/mYnESY4Md5 its common problem, wait until it will be fixed. If some one share mirror servers that duplicate RYDa data storage from https://returnyoutubedislike.com/ I can add them as alternative data sources for this cases.

**Comment by WyattLife** [comment]
It's working now
