### ISSUE TITLE
Dislike counter appears in wrong position on youtube mobile website

### ISSUE THREAD

**Issue by Tarshis** [NC22/KellyC-Show-YouTube-Dislikes#15]
I'm using Kiwi Browser to use this extension on the youtube mobile website. It has worked flawlessly for many months however in recent days it's become misaligned.

![Screenshot_20230507_104243_Kiwi Browser.png](https://user-images.githubusercontent.com/42141072/236670004-1828caac-b403-4eb5-b237-cec06de5c432.png)

**Comment by NC22** [comment]
thanks for notice. They updated layout a bit. Uploaded new version, they (store moderation) usually approve versions in few days.
