### ISSUE TITLE
Dislikes appear in the "Share" bubble instead of the regular dislike bubble.

### ISSUE THREAD

**Issue by NBruderman** [NC22/KellyC-Show-YouTube-Dislikes#19]
For some reason, today dislikes began to appear in the "Share" bubble instead of the regular dislike bubble.
I guess youtube changed the layout again. Here's an example

![Screenshot 2023-11-30 010647](https://github.com/NC22/KellyC-Show-YouTube-Dislikes/assets/6445601/107e51a0-45ab-48b7-bda8-e477b6ce2afb)

**Comment by NBruderman** [comment]
I see there is a new patch out that wasn't deployed to the store yet,
so I'll wait until it's out, and re-open if necessary.

**Comment by NC22** [comment]
@NBruderman Hi. Did you use Edge ? Yes, I already upload there update too, but they usually review new versions from 7 to 30 days, even on any small changes. You can try to delete and reinstall extension from chrome store https://chromewebstore.google.com/detail/kellyc-show-youtube-disli/gmdihkflccbodfkfioifolcijgahdgaf/reviews?hl=en

**Comment by NBruderman** [comment]
You were spot on!
I do use Edge, and after installing from chrome store, the updated version was installed, which solved the problem.
Thank you for the quick answer (and fix)
