### ISSUE TITLE
Dislike count being shown on the Share button instead of the Dislike button

### ISSUE THREAD

**Issue by N0bleSix** [NC22/KellyC-Show-YouTube-Dislikes#20]
According to a posting on the Git of the Return YouTube Dislike extension, this problem is happening with their extension also. To provide context as to why this may be happening, here is the posting I'm referring to: https://github.com/Anarios/return-youtube-dislike/issues/990#issuecomment-1832805944
![Screenshot 2023-11-30 183550](https://github.com/NC22/KellyC-Show-YouTube-Dislikes/assets/152566041/3a708284-5b26-4a88-96b6-8368f7740482)

**Comment by N0bleSix** [comment]
> @N0bleSix Hi. Thank you for report. It was fixed few days ago here [5ef7949](https://github.com/NC22/KellyC-Show-YouTube-Dislikes/commit/5ef794900f60b97910750a01f0de5927df3e99c5)
> 
> Also update depends on browser \ moderation process - [#19 (comment)](https://github.com/NC22/KellyC-Show-YouTube-Dislikes/issues/19#issuecomment-1832864603)
> 
> Current version is 1.1.6.4 but it can be not confirmed by moderation of extension store (currently new version approved only in Chrome \ FF store) \ or not automaticly updated

How long do you think until the update will be approved for the Microsoft Edge-Addons store?

**Comment by NC22** [comment]
@N0bleSix they shop says "5 business days", but sometimes longer - usually from 7 to 30 actual days

**Comment by N0bleSix** [comment]
> @N0bleSix they shop says "5 business days", but sometimes longer - usually from 7 to 30 actual days

Gotcha. For now, I'll just use the Chrome Web Store version until its approved for Microsoft's version. Thanks for all the work you do.
