### ISSUE TITLE
Extension Broke Recently

### ISSUE THREAD

**Issue by jabcreations** [NC22/KellyC-Show-YouTube-Dislikes#21]
Greetings. This was the only extension in Firefox that was working for the past few months after I figured out how to clean up Firefox. I imagine something along the lines of an API break, probably intentionally.

**Comment by Rin-Rem** [comment]
broke in chrome too. can confirm.

**Comment by jabcreations** [comment]
Hm, maybe it's not broken? I can see it working fine here:
https://www.youtube.com/watch?v=G35efdZUpvM

Perhaps it's an issue with people disabling the dislike button? I've seen it stated as being outright disabled.
