### ISSUE TITLE
No longer displays data

### ISSUE THREAD

**Issue by Janmm14** [NC22/KellyC-Show-YouTube-Dislikes#4]
i can see js console log outputs showing sucessful data query, but it seems to no longer fidn the youtube dislike buttons to display the line and it also doesnt change the dislike to the number.

**Comment by NC22** [comment]
Hi. currently cant see any problems from my current layout. 

Possibly this is some thing similar to https://github.com/NC22/KellyC-Show-YouTube-Dislikes/issues/3

Can you describe your setup : is any other extensions installed \ is desktop or mobile \ what browser / country or vpn is used.

Youtube can update its layout for testing upgrades only on selected countries.

**Comment by Janmm14** [comment]
Yeah seems like my main youtube account is part of an experiment. changed yt accounts for testing and it was visible like before.

Is this maybe enough information to make kellyc usable again? (i like its display way more than original ryd extension)
![firefox_100](https://user-images.githubusercontent.com/3533175/167208314-cf7b495c-d0b7-4b55-9278-35518abf900b.png)

visible design change is that the whole interaction bsa with like, dislike share, clip etc is displayed on the left below the description

**Comment by NC22** [comment]
Thanks for feedback. as I see this is the same new layout that was noticed in issue 3. By just this part of code cant see any new elements, but if now its not work there is still some thing was changed... will try to add more common selector as fall back when I'll be on my work place (after 10 of may)

**Comment by NC22** [comment]
fixed
