### ISSUE TITLE
Option to show full like and dislike count

### ISSUE THREAD

**Issue by iammark2** [NC22/KellyC-Show-YouTube-Dislikes#6]
Would it be possible to have an option to show the full like and dislike count instead of the shortened version, the way it used to be on YouTube before the polymer update?

Example:
Show 1,524,553 instead of 1.5M

Thanks!

**Comment by NC22** [comment]
Hi. Its nice option. Currently looks ok without any big modifications, just few lines of code, so I can add this as an optional setting on some of new versions for tests and will keep this if it wont cause any problems. I'll notify on update if so

**Comment by NC22** [comment]
@iammark2 Hi. Now added in public release also since version 1.1.5.0. in extension settings - Addition Options -> Show full counters

version 1.1.5.0 currently FF only, Chrome - in moderation process 1-2 days

**Comment by iammark2** [comment]
Tested and working on Firefox, thank you
