### ISSUE TITLE
Yet another youtube redesign layout

### ISSUE THREAD

**Issue by Janmm14** [NC22/KellyC-Show-YouTube-Dislikes#9]
And unfortunaly kellyc doesn't work with that again :/
> ![grafik](https://user-images.githubusercontent.com/3533175/197633551-397fd41b-cbe6-42d1-87ae-07177b8ae571.png)

HTML from devtools:
![grafik](https://user-images.githubusercontent.com/3533175/197634230-1d92d18d-5e3b-4845-bc62-28ef5598b2ef.png)

**Comment by NC22** [comment]
@Janmm14  thanks. noted in 1.1.5.1. available in FF

**Comment by Janmm14** [comment]
@NC22 Unfortunaly that doesn't seem to be working. Debug says `env exception 1`, finds buttonswrapper, and then there is `env exception 2 - use alternatve btncounter selector`. nothing more and neither the counter nor the bar shows up

**Comment by NC22** [comment]
@Janmm14 fixed possible reason in 1.1.5.2

**Comment by Janmm14** [comment]
@NC22 Thanks, its working now!
